Repository stackabletech/airflow-operator, pull requests merged in 2025-07, with the labels that each got.

#656 chore: Bump Rust dependencies pre-25.7.0
  CHANGELOG.md
  Cargo.lock
  Cargo.nix
  Cargo.toml
  crate-hashes.json
  deploy/helm/airflow-operator/crds/crds.yaml
  deploy/helm/airflow-operator/templates/roles.yaml
  rust/operator-binary/src/airflow_controller.rs
  rust/operator-binary/src/crd/mod.rs
  rust/operator-binary/src/main.rs
Labels: release/25.7.0

#653 Fix: headless svc for all roles as connection requires
  rust/operator-binary/src/airflow_controller.rs
  rust/operator-binary/src/service.rs
Labels: release-note, release/25.7.0

#660 fix: Add RBAC permission to patch events
  CHANGELOG.md
  deploy/helm/airflow-operator/templates/roles.yaml
Labels: scheduled-for/25.7.0
